### ISSUE TITLE
RedmineGitHosting::Commands errors after update to 6.0

### ISSUE THREAD

**Issue by soeren-helbig** [redmine-git-hosting/redmine_git_hosting#824]
Updated Redmine (4.2 to 5.0.5) & redmine-git-hosting (4.0.2 to 6.0.0). When opening Redmine Git Hosting configuration page (via admin menu), the following error occurs:

```
I, [2023-04-21T15:43:13.143131 #22]  INFO -- : Started GET "/settings/plugin/redmine_git_hosting" for 146.0.102.52 at 2023-04-21 15:43:13 +0000
I, [2023-04-21T15:43:13.144077 #22]  INFO -- : Processing by SettingsController#plugin as HTML
I, [2023-04-21T15:43:13.144113 #22]  INFO -- :   Parameters: {"id"=>"redmine_git_hosting"}
I, [2023-04-21T15:43:13.149992 #22]  INFO -- :   Current user: XXX (id=XXX)
I, [2023-04-21T15:43:13.264378 #22]  INFO -- :   Rendered settings/plugin.html.erb within layouts/admin (Duration: 113.6ms | Allocations: 13759)
I, [2023-04-21T15:43:13.264431 #22]  INFO -- :   Rendered layout layouts/admin.html.erb (Duration: 113.6ms | Allocations: 13788)
I, [2023-04-21T15:43:13.264701 #22]  INFO -- : Completed 500 Internal Server Error in 121ms (ActiveRecord: 2.8ms | Allocations: 15148)
F, [2023-04-21T15:43:13.265652 #22] FATAL -- :   
ActionView::Template::Error (undefined method `sudo_get_git_global_params' for RedmineGitHosting::Commands:Module

        RedmineGitHosting::Commands.sudo_get_git_global_params namespace
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Did you mean?  sudo_get_dir_size):
    44:       - else
    45:         = image_tag 'exclamation.png'
    46: 
    47:   - gitolite_checks = RedmineGitHosting::Config.check_hooks_install!
    48: 
    49:   tr
    50:     td = l :label_gitolite_hooks_installed
  
plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_params/base_param.rb:11:in `get_git_config_params'
plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_params/global_params.rb:20:in `initialize'
plugins/redmine_git_hosting/lib/redmine_git_hosting/config/gitolite_hooks.rb:43:in `new'
plugins/redmine_git_hosting/lib/redmine_git_hosting/config/gitolite_hooks.rb:43:in `check_hooks_install!'
plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_test.html.slim:47
app/views/common/_tabs.html.erb:21
app/views/common/_tabs.html.erb:20:in `each'
app/views/common/_tabs.html.erb:20
app/helpers/application_helper.rb:497:in `render_tabs'
plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.slim:22
app/views/settings/plugin.html.erb:6
app/views/settings/plugin.html.erb:4
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

```
Environment:
  Redmine version                5.0.5.stable
  Ruby version                   3.1.4-p223 (2023-03-30) [x86_64-linux]
  Rails version                  6.1.7.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Subversion                     1.14.1
  Mercurial                      5.6.1
  Bazaar                         3.1.0
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  additionals                    3.0.8
  redmine_agile                  1.6.5
  redmine_auto_percent           0.0.2
  redmine_checklists             3.1.22
  redmine_drawio                 1.4.6
  redmine_git_hosting            6.0.0
  redmine_people                 1.6.3
  redmine_theme_changer          0.6.0
  redmine_wysiwyg_editor         0.28.0
  view_customize                 3.3.0
```
